### ISSUE TITLE
SIR model understanding

### ISSUE THREAD

**Issue by amasend** [amasend/SIR-simulation-IBM-ESI#1]
This epic is created to make an introduction to the basic SIR model. Explain what it is, why we are using it, why it is really good for visualization. Student should explore different materials about SIR model in the internet and gain knowledge that further will be presented on front of the audience.

- [x] Make an introduction to SIR mathematical model

- [x] Pass learning materials

- [x] Knowledge checks during learning

- [x] Small presentation
