### ISSUE TITLE
SIR model simulation basic Python implementation

### ISSUE THREAD

**Issue by amasend** [amasend/SIR-simulation-IBM-ESI#2]
Make an implementation of the SIR model (basic scenario) in Python.
The scenario should include implementation of needed abstract classes with entire project structure.
SIR model simulation should be made with Object Oriented Python style. Unit tests should be included to check basic functionality of particular classes/methods etc.

- [x] Pycharm as IDE

- [x] Anaconda ENVs as workspace

- [x] Basic Unit tests for introductory class/method

- [x] Project structure creation

- [x] Programming API structure with abstract classes

- [x] Implementation of SIR model (simulation of epidemic)

- [x] Unit tests / TDD explenation
